/* Generated by Yosys 0.47+121 (git sha1 98b4affc4, g++ 13.2.0-23ubuntu4 -fPIC -O3) */

module demux_case(o0, o1, o2, o3, o4, o5, o6, o7, sel, i);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _40_;
  wire _41_;
  wire _42_;
  wire _43_;
  input i;
  wire i;
  output o0;
  wire o0;
  output o1;
  wire o1;
  output o2;
  wire o2;
  output o3;
  wire o3;
  output o4;
  wire o4;
  output o5;
  wire o5;
  output o6;
  wire o6;
  output o7;
  wire o7;
  input [2:0] sel;
  wire [2:0] sel;
  wire [7:0] y_int;
  sky130_fd_sc_hd__and4b_1 _44_ (
    .A_N(_41_),
    .B(_32_),
    .C(_43_),
    .D(_42_),
    .X(_39_)
  );
  sky130_fd_sc_hd__nor4b_1 _45_ (
    .A(_43_),
    .B(_42_),
    .C(_41_),
    .D_N(_32_),
    .Y(_33_)
  );
  sky130_fd_sc_hd__and4b_1 _46_ (
    .A_N(_42_),
    .B(_41_),
    .C(_32_),
    .D(_43_),
    .X(_38_)
  );
  sky130_fd_sc_hd__nor4bb_1 _47_ (
    .A(_42_),
    .B(_41_),
    .C_N(_32_),
    .D_N(_43_),
    .Y(_37_)
  );
  sky130_fd_sc_hd__and4b_1 _48_ (
    .A_N(_43_),
    .B(_42_),
    .C(_41_),
    .D(_32_),
    .X(_36_)
  );
  sky130_fd_sc_hd__nor4bb_1 _49_ (
    .A(_43_),
    .B(_42_),
    .C_N(_41_),
    .D_N(_32_),
    .Y(_34_)
  );
  sky130_fd_sc_hd__nor4bb_1 _50_ (
    .A(_43_),
    .B(_41_),
    .C_N(_32_),
    .D_N(_42_),
    .Y(_35_)
  );
  sky130_fd_sc_hd__and4_1 _51_ (
    .A(_43_),
    .B(_42_),
    .C(_41_),
    .D(_32_),
    .X(_40_)
  );
  assign y_int = { o7, o6, o5, o4, o3, o2, o1, o0 };
  assign _43_ = sel[2];
  assign _42_ = sel[1];
  assign _41_ = sel[0];
  assign _32_ = i;
  assign o6 = _39_;
  assign o0 = _33_;
  assign o5 = _38_;
  assign o4 = _37_;
  assign o3 = _36_;
  assign o1 = _34_;
  assign o2 = _35_;
  assign o7 = _40_;
endmodule
