/* Generated by Yosys 0.47+121 (git sha1 98b4affc4, g++ 13.2.0-23ubuntu4 -fPIC -O3) */

module counter_opt(clk, reset, q);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire [2:0] _13_;
  wire [2:0] _14_;
  input clk;
  wire clk;
  wire [2:0] count;
  output q;
  wire q;
  input reset;
  wire reset;
  sky130_fd_sc_hd__clkinv_1 _15_ (
    .A(_07_),
    .Y(_04_)
  );
  sky130_fd_sc_hd__clkinv_1 _16_ (
    .A(_12_),
    .Y(_03_)
  );
  sky130_fd_sc_hd__nor3b_1 _17_ (
    .A(_07_),
    .B(_08_),
    .C_N(_09_),
    .Y(_11_)
  );
  sky130_fd_sc_hd__nand2_1 _18_ (
    .A(_07_),
    .B(_08_),
    .Y(_10_)
  );
  sky130_fd_sc_hd__xor2_1 _19_ (
    .A(_07_),
    .B(_08_),
    .X(_05_)
  );
  sky130_fd_sc_hd__xnor2_1 _20_ (
    .A(_09_),
    .B(_10_),
    .Y(_06_)
  );
  sky130_fd_sc_hd__dfrtp_1 _21_ (
    .CLK(clk),
    .D(_13_[0]),
    .Q(count[0]),
    .RESET_B(_00_)
  );
  sky130_fd_sc_hd__dfrtp_1 _22_ (
    .CLK(clk),
    .D(_14_[1]),
    .Q(count[1]),
    .RESET_B(_00_)
  );
  sky130_fd_sc_hd__dfrtp_1 _23_ (
    .CLK(clk),
    .D(_14_[2]),
    .Q(count[2]),
    .RESET_B(_00_)
  );
  assign _13_[2:1] = count[2:1];
  assign _14_[0] = _13_[0];
  assign _07_ = count[0];
  assign _13_[0] = _04_;
  assign _08_ = count[1];
  assign _09_ = count[2];
  assign q = _11_;
  assign _14_[1] = _05_;
  assign _14_[2] = _06_;
  assign _12_ = reset;
  assign _00_ = _03_;
endmodule
