/* Generated by Yosys 0.47+121 (git sha1 98b4affc4, g++ 13.2.0-23ubuntu4 -fPIC -O3) */

module counter_opt(clk, reset, q);
  wire _0_;
  wire _1_;
  wire [2:0] _2_;
  input clk;
  wire clk;
  wire [2:0] count;
  output q;
  wire q;
  input reset;
  wire reset;
  sky130_fd_sc_hd__clkinv_1 _3_ (
    .A(_1_),
    .Y(_0_)
  );
  reg \count_reg[0] ;
  always @(posedge clk, posedge reset)
    if (reset) \count_reg[0]  <= 1'h0;
    else \count_reg[0]  <= _2_[0];
  assign count[0] = \count_reg[0] ;
  assign _2_[2:1] = count[2:1];
  assign q = count[0];
  assign _1_ = count[0];
  assign _2_[0] = _0_;
endmodule
