/* Generated by Yosys 0.47+121 (git sha1 98b4affc4, g++ 13.2.0-23ubuntu4 -fPIC -O3) */

module dff_const5(clk, reset, q);
  input clk;
  wire clk;
  output q;
  reg q;
  reg q1;
  input reset;
  wire reset;
  always @(posedge clk, posedge reset)
    if (reset) q <= 1'h0;
    else q <= q1;
  always @(posedge clk, posedge reset)
    if (reset) q1 <= 1'h0;
    else q1 <= 1'h1;
endmodule
