/* Generated by Yosys 0.47+121 (git sha1 98b4affc4, g++ 13.2.0-23ubuntu4 -fPIC -O3) */

module multiple_module_opt2(a, b, c, d, y);
  wire \U1.a ;
  wire \U1.b ;
  wire \U1.y ;
  wire \U2.a ;
  wire \U2.b ;
  wire \U3.b ;
  wire \U4.b ;
  wire \U4.y ;
  input a;
  wire a;
  input b;
  wire b;
  input c;
  wire c;
  input d;
  wire d;
  wire n1;
  output y;
  wire y;
  assign \U1.a  = a;
  assign \U1.b  = 1'h0;
  assign \U1.y  = 1'h0;
  assign \U2.a  = b;
  assign \U2.b  = c;
  assign \U3.b  = d;
  assign \U4.b  = 1'h0;
  assign \U4.y  = 1'h0;
  assign n1 = 1'h0;
  assign y = 1'h0;
endmodule
