/* Generated by Yosys 0.47+121 (git sha1 98b4affc4, g++ 13.2.0-23ubuntu4 -fPIC -O3) */

module multiple_module_opt(a, b, c, d, y);
  wire \U1.a ;
  wire \U1.b ;
  input a;
  wire a;
  input b;
  wire b;
  input c;
  wire c;
  input d;
  wire d;
  output y;
  wire y;
  sky130_fd_sc_hd__a21o_1 _0_ (
    .A1(b),
    .A2(a),
    .B1(c),
    .X(y)
  );
  assign \U1.a  = a;
  assign \U1.b  = 1'h1;
endmodule
